before_script:
  - psql -c 'create database soshigal_test;' -U postgres
script:
  - bundle exec rake db:test:prepare spec
bundler_args: --without development
language: ruby
rvm:
  - 1.9.3
notifications:
  recipients:
    - gray.manley@gmail.com
branches:
  only:
    - master
