development:
  adapter: postgresql
  database: loggia_development
  host: localhost

test:
  adapter: postgresql
  database: loggia_test
  <%= 'username: postgres' if ENV['travis'] %>

production:
  adapter: postgresql
  database: loggia_production
