development:
  adapter: postgresql
  database: soshigal_development

test:
  adapter: postgresql
  database: soshigal_test
  <%= 'username: postgres' if ENV['travis'] %>

production:
  adapter: postgresql
  database: soshigal_production
