development:
  adapter: postgresql
  database: soshigal_development

test:
  adapter: postgresql
  database: soshigal_test
  username: postgres

production:
  adapter: postgresql
  database: soshigal_production
