development:
  sessions:
    default:
      database: soshigal_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
test:
  sessions:
    default:
      database: soshigal_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
