shared: &shared_settings
  identity_map_enabled: true

development:
  <<: *shared_settings
  host: localhost
  database: soshigal_development

test:
  <<: *shared_settings
  host: localhost
  database: soshigal_test

production:
  <<: *shared_settings
  host: localhost
  database: soshigal_production